[package]
name = "pulso"
version = "0.1.0"
description = "Menubar app for project commands"
authors = ["sthbryan"]
edition = "2021"

[lib]
name = "pulso_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "tray-icon", "image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.40.2", features = ["bundled"] }
libc = "0.2.189"
tokio = { version = "1.53.1", features = ["process", "time", "rt", "sync", "io-util"] }
yaml-rust2 = "0.13.0"
toml = "1.1.6"
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"

[dev-dependencies]
tauri = { version = "2", features = ["test"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
